baseURL = "https://maisatanel.com"
theme = 'hugo-bearblog'

title = "maisatanel"
author = "Lina"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-GB"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Lina's space"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "maisatanel"
  hideMadeWithLine = true
